# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(712, 435)
        self.Title_edit = QtWidgets.QLabel(Form)
        self.Title_edit.setGeometry(QtCore.QRect(270, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Title_edit.setFont(font)
        self.Title_edit.setAutoFillBackground(False)
        self.Title_edit.setTextFormat(QtCore.Qt.PlainText)
        self.Title_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_edit.setWordWrap(False)
        self.Title_edit.setObjectName("Title_edit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 50, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Details_1 = QtWidgets.QLabel(Form)
        self.Details_1.setGeometry(QtCore.QRect(20, 350, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Details_1.setFont(font)
        self.Details_1.setObjectName("Details_1")
        self.Details_2 = QtWidgets.QLabel(Form)
        self.Details_2.setGeometry(QtCore.QRect(20, 370, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Details_2.setFont(font)
        self.Details_2.setObjectName("Details_2")
        self.Details_3 = QtWidgets.QLabel(Form)
        self.Details_3.setGeometry(QtCore.QRect(20, 390, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Details_3.setFont(font)
        self.Details_3.setObjectName("Details_3")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(410, 200, 301, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title_edit.setText(_translate("Form", "Welcome "))
        self.label.setText(_translate("Form", "Patient Regestration Kiosk v1.0"))
        self.Details_1.setText(_translate("Form", "Project : Medical Record Maintanence Bot"))
        self.Details_2.setText(_translate("Form", "Team : Shashank K S, Mahesh M, Srinivas U Bhat, Tejas Patil"))
        self.Details_3.setText(_translate("Form", "Guide : Prof. T S Chandar"))
        self.commandLinkButton.setText(_translate("Form", "Press this Button to continue"))
        self.commandLinkButton.setShortcut(_translate("Form", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
